### ISSUE TITLE
Create "about" page

### ISSUE THREAD

**Issue by adi64** [bptlab/gryphon#16]
There is a link to an "about" page, but there is no content. Either provide another location that this links to or write up some text for this page.

**Comment by marhew** [comment]
Please use the following text for the page:

The Gryphon case modeler is a tool for modeling case models developed by the [Business Process Technology group](https://bpt.hpi.uni-potsdam.de) at the Hasso Plattner Institute, University of Potsdam. Development started in spring 2016 as part of a Bachelor project. The code can be found at github: https://github.com/bptlab/Gryphon, the user documentation can be found at https://bptlab.github.io/Gryphon. 

It is based on the open source framework [bpmn.io](https://bpmn.io) maintained by [Camunda](https://camunda.com).

**Comment by adi64** [comment]
Implemented as a modal
