### ISSUE TITLE
Self-loops in OLC

### ISSUE THREAD

**Issue by marhew** [bptlab/gryphon#18]
As a case modeler I want to be able to express that an activity reads and writes a data object without changing it states. To do so, the state of the data object is the same in the preceding and succeeding data node of the activity. However, Gryphon complains about the missing state transition "X-> X" in the OLCbecause it is not possible for a state in the OLC to be both source and target of an arc.

**Comment by adi64** [comment]
As far as I understand, the way to go would be to change the validation logic to allow those "state transitions" even if they are not present in the OLC. Right?
This might spawn problems later on, as other software working with the model could choke like Gryphon does now...

**Comment by marhew** [comment]
**I want to model self-loops in OLCs with Gryphon**. To do this, you've got to change bpmn.io to allow arcs between blank intermediate events (because that is what we use for the states in OLCs). A better way would be to define a new model element `OLC state` with initial and terminal states and transitions including self-loops. But this requires some Javascript knowledge. However, bpmn.io has a nice meta-model based approach and tons of examples on their github https://github.com/bpmn-io/bpmn-js-examples.

Only specified activities in the process fragments should be able to change a DO without changing its state. Exactly then, when the activity has `DO [state]` as both data pre- and post-condition (formally, if there is a `(DO, state)` tuple in the intersection of input and output set). In such case, there needs to be a self-loop modeled in the OLC of `DO`. This **should be checked by the validation logic** (activity olc conformance).

Hope, this clears things up 😸

**Comment by marhew** [comment]
This seems to work in the dev branch, although it does not work in https://bpt-lab.org/gryphon-dev, as the docker image seems not to be rebuild or not redeployed.
