### ISSUE TITLE
tooltips for main functions

### ISSUE THREAD

**Issue by marhew** [bptlab/gryphon#2]
As a case modeler I want to start using Gryphon right away without having to read user manuals. Therefore, I need tooltips that explain the main functions of Gryphon when hovering the pointer above an element. Elements that provide a tooltip should be indicated with an (i) icon (small letter 'i' inside a circle).

**List of elements** that should have a tooltip (sorted by the view they appear on)
- [ ] 'add termination condition' (what is a termination condition, how should it look like)
- [ ] 'add start trigger' (what is a case start trigger)
- [ ] 'event query' label in a case start trigger (what is an event query and how should it look like)
- [ ] 'map another data class' in a case start trigger (explain that a data object of that class will be created as effect of the trigger)
- [ ] 'JSON path' in a case start trigger (how does the syntax look like)
- [ ] dropdown menu in data class view (explain difference between event and data)
- [ ] OLC editor (what is the OLC, how should it look like)
- [ ] 'add target' in export dialog

**Comment by adi64** [comment]
I am not feeling completely comfortable just writing up the tooltip texts because I'm not too familiar with the details - @marhew could you maybe provide the help texts or lead me to documentation where that is described?

**Comment by marhew** [comment]
- 'add termination condition' - _A case can terminate if one of its termination conditions is fulfilled. Each termination condition specifies that certain data objects need to be in a specific state, e.g. `Application[archived], CreditCard[activated]`._
- 'add start trigger' - _Case start triggers automatically instantiate cases whenever a specified external event occurs._
- 'event query' label in a case start trigger - _This Esper EPL query will be registered with Unicorn. When a matching event occurs, the case start trigger will be triggered and instantiate a new case_ 
- 'map another data class' in a case start trigger - _If data classes are added to the mapping the case start trigger will create data objects of that classes in the specified lifecycle state_
- 'JSON path' in a case start trigger - _The JsonPath expression is applied to the event matching the event query and the resulting values are stored in the specified data object attributes_
- dropdown menu in data class view  - _Data classes store information available in a case. Event classes specify expected external events and are registered with Unicorn._
- OLC editor - _This editor allows to model the object lifecycle (OLC) of a data class. The OLC defines states and valid state transitions for data objects of that data class. Fragments are validated against the OLC, e.g. no activities are allowed to change the state of a data object if this transition is not allowed in the OLC._
- 'add target' in export dialog - _Enter the endpoint for the REST API of the Chimera instance you want to connect, e.g. `http://localhost:8080/Chimera/api/interface/v2`._
