### ISSUE TITLE
Change the way Event Classes work

### ISSUE THREAD

**Issue by marhew** [bptlab/gryphon#20]
As a modeler I do not want to distinguish between data and event classes. Rather, I would like for them to behave the same with the exception that event classes are registered with Unicorn and can be used as input for throwing events.

- no distinction when creating data classes (up to now, I can choose between data and event class)
- no drop-down in the data class view to switch between data and event class
- instead, there should be a checkbox "use as event type" to indicate whether a data class is to be registered with Unicorn

**Comment by adi64** [comment]
Does anything need to change in Gryphon besides the already mentioned change from a dropdown to a checkbox and the modal dialog? Event classes still don't have an OLC, right?

**Comment by marhew** [comment]
"Event classes", i.e. data classe with the "use as event type" checkbox ticked, are usual data classes and thus **they have an OLC**. From Gryphon's perspective there is no difference except the checkbox. The way data classes are serialized as Json to be sent to Chimera should be fine.
