### ISSUE TITLE
add 'header' attribute for webservice tasks

### ISSUE THREAD

**Issue by marhew** [bptlab/gryphon#28]
To support header-based authentication in webservice task, I need a way to model the headers that should be send in a REST request to a webservice. The properties panel in the bpmn.io modeling component need to be extended with an additional attribute 'header'.

The properties of a BPMN element are defined in gryphon/public_src/js/bpmn/provider.js in the function `createWebServiceTaskProperties`. Additionally, the WebServiceTask definition in gryphon/public_src/js/bpmn/bpmnextension.json needs to be adapted to ensure that the new property is exported in the BPMN xml.

**Comment by marhew** [comment]
That was easy. Actually, it took me longer to write this story than to implement the feature.

**Comment by tommartensen** [comment]
Nice! Is this also implemented in Gryphon?

**Comment by tommartensen** [comment]
Nice! Should we do the implementation in Chimera then?
