### ISSUE TITLE
export fragment pre-conditions to Chimera

### ISSUE THREAD

**Issue by marhew** [bptlab/gryphon#8]
As a case modeler I want to model data pre-conditions for fragments. Modeling is covered in #6, storage in #7, while this issue deals with exporting the pre-conditions to Chimera. The JSON serialization sent by gryphon to chimera needs to be extended with the pre-conditions. This is very similar to the termination conditions!

**Acceptance Criteria**
- fragment pre-conditions are part of the JSON serialization produced by the export in Gryphon

**Comment by adi64** [comment]
This is also done by 40d946a99cdfb38171cc8511eb2dee022ac69a9e, although I am not completely sure if the format is correct.
